apiVersion: v1
kind: Service
metadata:
  name: {{ include "employeeapp.fullname" . }}
  labels:
    {{- include "employeeapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "employeeapp.selectorLabels" . | nindent 4 }}
