pipeline {
    agent any

    stages {
        stage(' Gradle Build and Test') {
            steps {
                echo 'Building..and Testing ...'
                script {
                    sh './gradlew clean build'
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}